//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InomiEntities : DbContext
    {
        public InomiEntities()
            : base("name=InomiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<interestinglink> interestinglinks { get; set; }
        public virtual DbSet<selectedcollege> selectedcolleges { get; set; }
        public virtual DbSet<studentmilestoneupload> studentmilestoneuploads { get; set; }
        public virtual DbSet<tblAcadenmouse> tblAcadenmice { get; set; }
        public virtual DbSet<tblAssingTask> tblAssingTasks { get; set; }
        public virtual DbSet<tblCallNote> tblCallNotes { get; set; }
        public virtual DbSet<tblCollege> tblColleges { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblCourse> tblCourses { get; set; }
        public virtual DbSet<tblExtraCurricularActivite> tblExtraCurricularActivites { get; set; }
        public virtual DbSet<tblFormat> tblFormats { get; set; }
        public virtual DbSet<tblLeadershipPosition> tblLeadershipPositions { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProject> tblProjects { get; set; }
        public virtual DbSet<tblStudent> tblStudents { get; set; }
        public virtual DbSet<tblTask> tblTasks { get; set; }
        public virtual DbSet<tblTest> tblTests { get; set; }
        public virtual DbSet<tblTestReport> tblTestReports { get; set; }
        public virtual DbSet<UploadEssayFile> UploadEssayFiles { get; set; }
        public virtual DbSet<tbl_ExcelFilePath> tbl_ExcelFilePath { get; set; }
        public virtual DbSet<tblApplicationMode> tblApplicationModes { get; set; }
        public virtual DbSet<tblCityName> tblCityNames { get; set; }
        public virtual DbSet<tblCollegeDetail> tblCollegeDetails { get; set; }
        public virtual DbSet<tblCollegeDetailsTemp> tblCollegeDetailsTemps { get; set; }
        public virtual DbSet<tblCollegeScore> tblCollegeScores { get; set; }
        public virtual DbSet<tblCounsellor> tblCounsellors { get; set; }
        public virtual DbSet<tblCountryName> tblCountryNames { get; set; }
        public virtual DbSet<tblEventTemp> tblEventTemps { get; set; }
        public virtual DbSet<tblFAQDetail> tblFAQDetails { get; set; }
        public virtual DbSet<tblFAQDetails_Temp> tblFAQDetails_Temp { get; set; }
        public virtual DbSet<tblFormatTemp> tblFormatTemps { get; set; }
        public virtual DbSet<tblGendor> tblGendors { get; set; }
        public virtual DbSet<tblMonth> tblMonths { get; set; }
        public virtual DbSet<tblPaymentDetail> tblPaymentDetails { get; set; }
        public virtual DbSet<tblPercentileName> tblPercentileNames { get; set; }
        public virtual DbSet<tblProjectMilestone> tblProjectMilestones { get; set; }
        public virtual DbSet<tblStudentInstallmentDetail> tblStudentInstallmentDetails { get; set; }
        public virtual DbSet<tblTestingRequirement> tblTestingRequirements { get; set; }
        public virtual DbSet<tblUsersLogIn> tblUsersLogIns { get; set; }
        public virtual DbSet<tblQuestionnaireCareerDescription> tblQuestionnaireCareerDescriptions { get; set; }
        public virtual DbSet<tblQuestionnaireCourseWork> tblQuestionnaireCourseWorks { get; set; }
        public virtual DbSet<tblQuestionnaireFieldLogic> tblQuestionnaireFieldLogics { get; set; }
        public virtual DbSet<tblQuestionnaireFieldLogicResult> tblQuestionnaireFieldLogicResults { get; set; }
        public virtual DbSet<tblQuestionnaireLogin> tblQuestionnaireLogins { get; set; }
        public virtual DbSet<tblQuestionnaireMainStrength> tblQuestionnaireMainStrengths { get; set; }
        public virtual DbSet<tblQuestionnaireOnlineCourse> tblQuestionnaireOnlineCourses { get; set; }
        public virtual DbSet<tblQuestionnaireReading> tblQuestionnaireReadings { get; set; }
        public virtual DbSet<tblQuestionnaireStudentRegister> tblQuestionnaireStudentRegisters { get; set; }
        public virtual DbSet<tblQuestionnaireSubStrength> tblQuestionnaireSubStrengths { get; set; }
        public virtual DbSet<tblQuestionnaireSubStrengthQuestion> tblQuestionnaireSubStrengthQuestions { get; set; }
        public virtual DbSet<tblQuestionnaireSubStrengthResult> tblQuestionnaireSubStrengthResults { get; set; }
        public virtual DbSet<tblQuestionnaireVideo> tblQuestionnaireVideos { get; set; }
    
        public virtual ObjectResult<sp_collegeshortlist_Result> sp_collegeshortlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_collegeshortlist_Result>("sp_collegeshortlist");
        }
    
        public virtual ObjectResult<EventList_Result> EventList(string loginId)
        {
            var loginIdParameter = loginId != null ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EventList_Result>("EventList", loginIdParameter);
        }
    
        [DbFunction("InomiEntities", "SplitString")]
        public virtual IQueryable<string> SplitString(string input, string character)
        {
            var inputParameter = input != null ?
                new ObjectParameter("Input", input) :
                new ObjectParameter("Input", typeof(string));
    
            var characterParameter = character != null ?
                new ObjectParameter("Character", character) :
                new ObjectParameter("Character", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[InomiEntities].[SplitString](@Input, @Character)", inputParameter, characterParameter);
        }
    
        public virtual ObjectResult<FilterData_Result> FilterData(string collegename, string country, string city, string course, string rank, string shortlist, string applictionthrough)
        {
            var collegenameParameter = collegename != null ?
                new ObjectParameter("collegename", collegename) :
                new ObjectParameter("collegename", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var courseParameter = course != null ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(string));
    
            var rankParameter = rank != null ?
                new ObjectParameter("rank", rank) :
                new ObjectParameter("rank", typeof(string));
    
            var shortlistParameter = shortlist != null ?
                new ObjectParameter("Shortlist", shortlist) :
                new ObjectParameter("Shortlist", typeof(string));
    
            var applictionthroughParameter = applictionthrough != null ?
                new ObjectParameter("applictionthrough", applictionthrough) :
                new ObjectParameter("applictionthrough", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FilterData_Result>("FilterData", collegenameParameter, countryParameter, cityParameter, courseParameter, rankParameter, shortlistParameter, applictionthroughParameter);
        }
    
        public virtual ObjectResult<FilterDataCouncellor_Result> FilterDataCouncellor(string studentid, string councellorid, string collegename, string country, string city, string course, string rank, string shortlist, string applictionthrough)
        {
            var studentidParameter = studentid != null ?
                new ObjectParameter("studentid", studentid) :
                new ObjectParameter("studentid", typeof(string));
    
            var councelloridParameter = councellorid != null ?
                new ObjectParameter("councellorid", councellorid) :
                new ObjectParameter("councellorid", typeof(string));
    
            var collegenameParameter = collegename != null ?
                new ObjectParameter("collegename", collegename) :
                new ObjectParameter("collegename", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var courseParameter = course != null ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(string));
    
            var rankParameter = rank != null ?
                new ObjectParameter("rank", rank) :
                new ObjectParameter("rank", typeof(string));
    
            var shortlistParameter = shortlist != null ?
                new ObjectParameter("Shortlist", shortlist) :
                new ObjectParameter("Shortlist", typeof(string));
    
            var applictionthroughParameter = applictionthrough != null ?
                new ObjectParameter("applictionthrough", applictionthrough) :
                new ObjectParameter("applictionthrough", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FilterDataCouncellor_Result>("FilterDataCouncellor", studentidParameter, councelloridParameter, collegenameParameter, countryParameter, cityParameter, courseParameter, rankParameter, shortlistParameter, applictionthroughParameter);
        }
    
        public virtual int ApproveBackStatus(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApproveBackStatus", idParameter, createdByParameter);
        }
    
        public virtual int ApprovedPaymentStatus(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApprovedPaymentStatus", idParameter, createdByParameter);
        }
    
        public virtual int ApproveStatusEssay(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApproveStatusEssay", idParameter, createdByParameter);
        }
    
        public virtual int DeleteAcedemicsDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAcedemicsDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteActivitiesDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteActivitiesDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteAssignTaskDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAssignTaskDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteCollegeDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCollegeDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteConAssignTaskDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteConAssignTaskDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteCounsellorDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCounsellorDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteCountryDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCountryDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteCourseDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCourseDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteFAQDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteFAQDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteFormatDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteFormatDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteLeadershipDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLeadershipDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteProductDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProductDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteProjectDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProjectDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteStudentDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteStudentDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteTaskDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTaskDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeletetestDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletetestDetails", idParameter, createdByParameter);
        }
    
        public virtual int DeleteTestScoreDetails(string id, string createdBy)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTestScoreDetails", idParameter, createdByParameter);
        }
    
        public virtual ObjectResult<EditAcedemicsDetails_Result> EditAcedemicsDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditAcedemicsDetails_Result>("EditAcedemicsDetails", idParameter);
        }
    
        public virtual ObjectResult<EditActivitiesDetails_Result> EditActivitiesDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditActivitiesDetails_Result>("EditActivitiesDetails", idParameter);
        }
    
        public virtual ObjectResult<EditCollegeDetails_Result> EditCollegeDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditCollegeDetails_Result>("EditCollegeDetails", idParameter);
        }
    
        public virtual ObjectResult<EditConAssignTaskDetails_Result> EditConAssignTaskDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditConAssignTaskDetails_Result>("EditConAssignTaskDetails", idParameter);
        }
    
        public virtual ObjectResult<EditCounsellorDetails_Result> EditCounsellorDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditCounsellorDetails_Result>("EditCounsellorDetails", idParameter);
        }
    
        public virtual ObjectResult<EditCountryDetails_Result> EditCountryDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditCountryDetails_Result>("EditCountryDetails", idParameter);
        }
    
        public virtual ObjectResult<EditCourseDetails_Result> EditCourseDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditCourseDetails_Result>("EditCourseDetails", idParameter);
        }
    
        public virtual ObjectResult<EditFormatDetails_Result> EditFormatDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditFormatDetails_Result>("EditFormatDetails", idParameter);
        }
    
        public virtual ObjectResult<EditLeadershipDetails_Result> EditLeadershipDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditLeadershipDetails_Result>("EditLeadershipDetails", idParameter);
        }
    
        public virtual ObjectResult<EditProductDetails_Result> EditProductDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditProductDetails_Result>("EditProductDetails", idParameter);
        }
    
        public virtual ObjectResult<EditProjectDetails_Result> EditProjectDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditProjectDetails_Result>("EditProjectDetails", idParameter);
        }
    
        public virtual ObjectResult<EditStudentDetails_Result> EditStudentDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditStudentDetails_Result>("EditStudentDetails", idParameter);
        }
    
        public virtual ObjectResult<EditTaskDetails_Result> EditTaskDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditTaskDetails_Result>("EditTaskDetails", idParameter);
        }
    
        public virtual ObjectResult<EditTestDetails_Result> EditTestDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditTestDetails_Result>("EditTestDetails", idParameter);
        }
    
        public virtual ObjectResult<EditTestScoreDetails_Result> EditTestScoreDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EditTestScoreDetails_Result>("EditTestScoreDetails", idParameter);
        }
    
        public virtual ObjectResult<GetAcedemicsDetails_Result> GetAcedemicsDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAcedemicsDetails_Result>("GetAcedemicsDetails");
        }
    
        public virtual ObjectResult<GetActivitiesDetails_Result> GetActivitiesDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActivitiesDetails_Result>("GetActivitiesDetails");
        }
    
        public virtual int GetActivity_Report(string str)
        {
            var strParameter = str != null ?
                new ObjectParameter("Str", str) :
                new ObjectParameter("Str", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetActivity_Report", strParameter);
        }
    
        public virtual int GetAdminAssignTaskDetails(string str, string usertypeId)
        {
            var strParameter = str != null ?
                new ObjectParameter("Str", str) :
                new ObjectParameter("Str", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAdminAssignTaskDetails", strParameter, usertypeIdParameter);
        }
    
        public virtual int GetApplicationChart(string countryId)
        {
            var countryIdParameter = countryId != null ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetApplicationChart", countryIdParameter);
        }
    
        public virtual ObjectResult<GetApplicationModeList_Result> GetApplicationModeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetApplicationModeList_Result>("GetApplicationModeList");
        }
    
        public virtual ObjectResult<GetApplicationYearList_Result> GetApplicationYearList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetApplicationYearList_Result>("GetApplicationYearList");
        }
    
        public virtual int GetAssignTask(string str, string usertypeId)
        {
            var strParameter = str != null ?
                new ObjectParameter("Str", str) :
                new ObjectParameter("Str", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAssignTask", strParameter, usertypeIdParameter);
        }
    
        public virtual ObjectResult<GetAssignTaskById_Result> GetAssignTaskById(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAssignTaskById_Result>("GetAssignTaskById", idParameter);
        }
    
        public virtual int GetAssignTaskDetails(string str, string usertypeId)
        {
            var strParameter = str != null ?
                new ObjectParameter("Str", str) :
                new ObjectParameter("Str", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAssignTaskDetails", strParameter, usertypeIdParameter);
        }
    
        public virtual ObjectResult<GetCalendarEventDetails_Result> GetCalendarEventDetails(string usertypeId, string userType)
        {
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCalendarEventDetails_Result>("GetCalendarEventDetails", usertypeIdParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<GetCityList_Result> GetCityList(Nullable<int> cID)
        {
            var cIDParameter = cID.HasValue ?
                new ObjectParameter("CID", cID) :
                new ObjectParameter("CID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCityList_Result>("GetCityList", cIDParameter);
        }
    
        public virtual ObjectResult<GetCollegeDetails_Result> GetCollegeDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCollegeDetails_Result>("GetCollegeDetails");
        }
    
        public virtual ObjectResult<GetCollegeEssayDetails_Result> GetCollegeEssayDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCollegeEssayDetails_Result>("GetCollegeEssayDetails", idParameter);
        }
    
        public virtual ObjectResult<GetCollegeList_Result> GetCollegeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCollegeList_Result>("GetCollegeList");
        }
    
        public virtual ObjectResult<GetCounsellerPendingTask_Result> GetCounsellerPendingTask()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCounsellerPendingTask_Result>("GetCounsellerPendingTask");
        }
    
        public virtual ObjectResult<GetCounsellerPendingTaskById_Result> GetCounsellerPendingTaskById(string usertypeId)
        {
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCounsellerPendingTaskById_Result>("GetCounsellerPendingTaskById", usertypeIdParameter);
        }
    
        public virtual int GetCounsellorDashboardStudent_Report(string str, string usertypeId)
        {
            var strParameter = str != null ?
                new ObjectParameter("Str", str) :
                new ObjectParameter("Str", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetCounsellorDashboardStudent_Report", strParameter, usertypeIdParameter);
        }
    
        public virtual ObjectResult<GetCounsellorDetails_Result> GetCounsellorDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCounsellorDetails_Result>("GetCounsellorDetails");
        }
    
        public virtual ObjectResult<GetCounsellorList_Result> GetCounsellorList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCounsellorList_Result>("GetCounsellorList");
        }
    
        public virtual ObjectResult<GetCountryDetails_Result> GetCountryDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountryDetails_Result>("GetCountryDetails");
        }
    
        public virtual ObjectResult<GetCountryList_Result> GetCountryList(string loginId)
        {
            var loginIdParameter = loginId != null ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountryList_Result>("GetCountryList", loginIdParameter);
        }
    
        public virtual ObjectResult<GetCourseDetails_Result> GetCourseDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCourseDetails_Result>("GetCourseDetails");
        }
    
        public virtual ObjectResult<GetCourseList_Result> GetCourseList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCourseList_Result>("GetCourseList");
        }
    
        public virtual ObjectResult<GetDashboardEventDetails_Result> GetDashboardEventDetails(string usertypeId, string userType)
        {
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDashboardEventDetails_Result>("GetDashboardEventDetails", usertypeIdParameter, userTypeParameter);
        }
    
        public virtual int GetDashboardStudent_Report(string str, string usertypeId)
        {
            var strParameter = str != null ?
                new ObjectParameter("Str", str) :
                new ObjectParameter("Str", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDashboardStudent_Report", strParameter, usertypeIdParameter);
        }
    
        public virtual int GetEmailDetails(string counsellorId, string studentId)
        {
            var counsellorIdParameter = counsellorId != null ?
                new ObjectParameter("CounsellorId", counsellorId) :
                new ObjectParameter("CounsellorId", typeof(string));
    
            var studentIdParameter = studentId != null ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetEmailDetails", counsellorIdParameter, studentIdParameter);
        }
    
        public virtual ObjectResult<GetEssayCount_Result> GetEssayCount(Nullable<int> cID)
        {
            var cIDParameter = cID.HasValue ?
                new ObjectParameter("CID", cID) :
                new ObjectParameter("CID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEssayCount_Result>("GetEssayCount", cIDParameter);
        }
    
        public virtual ObjectResult<GetEssayDetails_Result> GetEssayDetails(Nullable<int> cID)
        {
            var cIDParameter = cID.HasValue ?
                new ObjectParameter("CID", cID) :
                new ObjectParameter("CID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEssayDetails_Result>("GetEssayDetails", cIDParameter);
        }
    
        public virtual ObjectResult<GetEventDetails_Result> GetEventDetails(string usertypeId, string userType)
        {
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventDetails_Result>("GetEventDetails", usertypeIdParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<GetFAQById_Result> GetFAQById(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFAQById_Result>("GetFAQById", idParameter);
        }
    
        public virtual ObjectResult<GetFAQDetail_Result> GetFAQDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFAQDetail_Result>("GetFAQDetail");
        }
    
        public virtual ObjectResult<GetFormatDetails_Result> GetFormatDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFormatDetails_Result>("GetFormatDetails");
        }
    
        public virtual ObjectResult<GetLeadershipDetails_Result> GetLeadershipDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLeadershipDetails_Result>("GetLeadershipDetails");
        }
    
        public virtual ObjectResult<GetMileStoneDefineDetails_Result> GetMileStoneDefineDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMileStoneDefineDetails_Result>("GetMileStoneDefineDetails", idParameter);
        }
    
        public virtual ObjectResult<GetMyProfile_Result> GetMyProfile(string usertypeId)
        {
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMyProfile_Result>("GetMyProfile", usertypeIdParameter);
        }
    
        public virtual ObjectResult<string> GetPathfinder(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetPathfinder", idParameter);
        }
    
        public virtual ObjectResult<GetPathfinderDetails_Result> GetPathfinderDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPathfinderDetails_Result>("GetPathfinderDetails");
        }
    
        public virtual int GetPaymentPending_Report(string str)
        {
            var strParameter = str != null ?
                new ObjectParameter("Str", str) :
                new ObjectParameter("Str", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetPaymentPending_Report", strParameter);
        }
    
        public virtual int GetProductChart(string productId, string tabId)
        {
            var productIdParameter = productId != null ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(string));
    
            var tabIdParameter = tabId != null ?
                new ObjectParameter("TabId", tabId) :
                new ObjectParameter("TabId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetProductChart", productIdParameter, tabIdParameter);
        }
    
        public virtual int GetProductChartCounsellorDashboard(string productId, string tabId, string usertypeId)
        {
            var productIdParameter = productId != null ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(string));
    
            var tabIdParameter = tabId != null ?
                new ObjectParameter("TabId", tabId) :
                new ObjectParameter("TabId", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetProductChartCounsellorDashboard", productIdParameter, tabIdParameter, usertypeIdParameter);
        }
    
        public virtual ObjectResult<GetProductDetails_Result> GetProductDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductDetails_Result>("GetProductDetails");
        }
    
        public virtual ObjectResult<GetProductList_Result> GetProductList(string loginId)
        {
            var loginIdParameter = loginId != null ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductList_Result>("GetProductList", loginIdParameter);
        }
    
        public virtual ObjectResult<GetProjectDetails_Result> GetProjectDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectDetails_Result>("GetProjectDetails");
        }
    
        public virtual ObjectResult<GetProjectMilestoneDetails_Result> GetProjectMilestoneDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectMilestoneDetails_Result>("GetProjectMilestoneDetails", idParameter);
        }
    
        public virtual int GetReport_Student(string str, string usertypeId)
        {
            var strParameter = str != null ?
                new ObjectParameter("Str", str) :
                new ObjectParameter("Str", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetReport_Student", strParameter, usertypeIdParameter);
        }
    
        public virtual ObjectResult<GetSchoolList_Result> GetSchoolList(string loginId)
        {
            var loginIdParameter = loginId != null ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSchoolList_Result>("GetSchoolList", loginIdParameter);
        }
    
        public virtual ObjectResult<GetScoreDetails_Result> GetScoreDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScoreDetails_Result>("GetScoreDetails", idParameter);
        }
    
        public virtual ObjectResult<GetScoreType_Result> GetScoreType(string loginId, string usertypeId)
        {
            var loginIdParameter = loginId != null ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScoreType_Result>("GetScoreType", loginIdParameter, usertypeIdParameter);
        }
    
        public virtual ObjectResult<GetStudentDetails_Result> GetStudentDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentDetails_Result>("GetStudentDetails");
        }
    
        public virtual ObjectResult<string> GetStudentEmailDetails(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetStudentEmailDetails", idParameter);
        }
    
        public virtual ObjectResult<GetStudentList_Result> GetStudentList(string loginId, string usertypeId)
        {
            var loginIdParameter = loginId != null ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentList_Result>("GetStudentList", loginIdParameter, usertypeIdParameter);
        }
    
        public virtual ObjectResult<GetTaskDetails_Result> GetTaskDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTaskDetails_Result>("GetTaskDetails");
        }
    
        public virtual ObjectResult<GetTestDetails_Result> GetTestDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTestDetails_Result>("GetTestDetails");
        }
    
        public virtual ObjectResult<GetTestingRequirementList_Result> GetTestingRequirementList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTestingRequirementList_Result>("GetTestingRequirementList");
        }
    
        public virtual ObjectResult<GetTestScoreDetails_Result> GetTestScoreDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTestScoreDetails_Result>("GetTestScoreDetails");
        }
    
        public virtual ObjectResult<GetToDoListEventDetails_Result> GetToDoListEventDetails(string usertypeId, string userType)
        {
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetToDoListEventDetails_Result>("GetToDoListEventDetails", usertypeIdParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<GetTotalApplication_Result> GetTotalApplication()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalApplication_Result>("GetTotalApplication");
        }
    
        public virtual ObjectResult<GetTotalApplicationById_Result> GetTotalApplicationById(string usertypeId)
        {
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalApplicationById_Result>("GetTotalApplicationById", usertypeIdParameter);
        }
    
        public virtual ObjectResult<GetUniversityName_Result> GetUniversityName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUniversityName_Result>("GetUniversityName");
        }
    
        public virtual int InsertAcedemicsDetails(string dataEntry, string id, string createdBy, string picture)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var pictureParameter = picture != null ?
                new ObjectParameter("Picture", picture) :
                new ObjectParameter("Picture", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAcedemicsDetails", dataEntryParameter, idParameter, createdByParameter, pictureParameter);
        }
    
        public virtual int InsertActivitiesDetails(string dataEntry, string id, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertActivitiesDetails", dataEntryParameter, idParameter, createdByParameter);
        }
    
        public virtual int InsertAdminAssignTaskDetails(string dataEntry, string id, string createdBy, string userRole)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("UserRole", userRole) :
                new ObjectParameter("UserRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAdminAssignTaskDetails", dataEntryParameter, idParameter, createdByParameter, userRoleParameter);
        }
    
        public virtual int InsertAssignTask(string dataEntry, string id, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAssignTask", dataEntryParameter, idParameter, createdByParameter);
        }
    
        public virtual int InsertAssignTaskDetails(string dataEntry, string id, string createdBy, string userRole)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("UserRole", userRole) :
                new ObjectParameter("UserRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAssignTaskDetails", dataEntryParameter, idParameter, createdByParameter, userRoleParameter);
        }
    
        public virtual int InsertCalendarEventDetails(string dataEntry, string usertypeId)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCalendarEventDetails", dataEntryParameter, usertypeIdParameter);
        }
    
        public virtual int InsertCollegeDetails(string dataEntry, string id, string dataEntryDetails, string dataScore, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var dataEntryDetailsParameter = dataEntryDetails != null ?
                new ObjectParameter("dataEntryDetails", dataEntryDetails) :
                new ObjectParameter("dataEntryDetails", typeof(string));
    
            var dataScoreParameter = dataScore != null ?
                new ObjectParameter("dataScore", dataScore) :
                new ObjectParameter("dataScore", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCollegeDetails", dataEntryParameter, idParameter, dataEntryDetailsParameter, dataScoreParameter, createdByParameter);
        }
    
        public virtual int InsertCollegeDetails_BackUp18Feb2020(string dataEntry, string id, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCollegeDetails_BackUp18Feb2020", dataEntryParameter, idParameter, createdByParameter);
        }
    
        public virtual int InsertCounsoellorDetails(string dataEntry, string id, string createdBy, string filePath)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCounsoellorDetails", dataEntryParameter, idParameter, createdByParameter, filePathParameter);
        }
    
        public virtual int InsertCounsoellorDetails_BackUp18Feb2020(string dataEntry, string id, string createdBy, string filePath)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCounsoellorDetails_BackUp18Feb2020", dataEntryParameter, idParameter, createdByParameter, filePathParameter);
        }
    
        public virtual int InsertCountryDetails(string dataEntry, string id, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCountryDetails", dataEntryParameter, idParameter, createdByParameter);
        }
    
        public virtual int InsertCourseDetails(string dataEntry, string id, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCourseDetails", dataEntryParameter, idParameter, createdByParameter);
        }
    
        public virtual int InsertEventDetails(string dataEntry, string usertypeId)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertEventDetails", dataEntryParameter, usertypeIdParameter);
        }
    
        public virtual int InsertFAQDetails(string dataEntry, string id, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertFAQDetails", dataEntryParameter, idParameter, createdByParameter);
        }
    
        public virtual int InsertFormatDetails(string dataEntry, string id, string createdBy, string filePath, string emailbody, string dataCon, string dataStu, string emailsubject, Nullable<int> filesize)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            var emailbodyParameter = emailbody != null ?
                new ObjectParameter("Emailbody", emailbody) :
                new ObjectParameter("Emailbody", typeof(string));
    
            var dataConParameter = dataCon != null ?
                new ObjectParameter("dataCon", dataCon) :
                new ObjectParameter("dataCon", typeof(string));
    
            var dataStuParameter = dataStu != null ?
                new ObjectParameter("dataStu", dataStu) :
                new ObjectParameter("dataStu", typeof(string));
    
            var emailsubjectParameter = emailsubject != null ?
                new ObjectParameter("Emailsubject", emailsubject) :
                new ObjectParameter("Emailsubject", typeof(string));
    
            var filesizeParameter = filesize.HasValue ?
                new ObjectParameter("Filesize", filesize) :
                new ObjectParameter("Filesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertFormatDetails", dataEntryParameter, idParameter, createdByParameter, filePathParameter, emailbodyParameter, dataConParameter, dataStuParameter, emailsubjectParameter, filesizeParameter);
        }
    
        public virtual int InsertLeadershipDetails(string dataEntry, string id, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLeadershipDetails", dataEntryParameter, idParameter, createdByParameter);
        }
    
        public virtual int InsertMyProfileAbout(string id, string phone, string country, string city, string filePath, string picture)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            var pictureParameter = picture != null ?
                new ObjectParameter("Picture", picture) :
                new ObjectParameter("Picture", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertMyProfileAbout", idParameter, phoneParameter, countryParameter, cityParameter, filePathParameter, pictureParameter);
        }
    
        public virtual int InsertMyProfileAchievement(string id, string achievement)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var achievementParameter = achievement != null ?
                new ObjectParameter("Achievement", achievement) :
                new ObjectParameter("Achievement", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertMyProfileAchievement", idParameter, achievementParameter);
        }
    
        public virtual int InsertMyProfileExperience(string id, string experience)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var experienceParameter = experience != null ?
                new ObjectParameter("Experience", experience) :
                new ObjectParameter("Experience", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertMyProfileExperience", idParameter, experienceParameter);
        }
    
        public virtual int InsertMyProfilelinksUp(string id, string linksUp)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var linksUpParameter = linksUp != null ?
                new ObjectParameter("linksUp", linksUp) :
                new ObjectParameter("linksUp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertMyProfilelinksUp", idParameter, linksUpParameter);
        }
    
        public virtual int InsertPathfinderDetails(string id, string createdBy, string picture, string dataEntry)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var pictureParameter = picture != null ?
                new ObjectParameter("Picture", picture) :
                new ObjectParameter("Picture", typeof(string));
    
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPathfinderDetails", idParameter, createdByParameter, pictureParameter, dataEntryParameter);
        }
    
        public virtual int InsertProductDetails(string dataEntry, string id, string createdBy, string picture)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var pictureParameter = picture != null ?
                new ObjectParameter("Picture", picture) :
                new ObjectParameter("Picture", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertProductDetails", dataEntryParameter, idParameter, createdByParameter, pictureParameter);
        }
    
        public virtual int InsertProjectDetails(string dataEntry, string id, string dataEntryDetails, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var dataEntryDetailsParameter = dataEntryDetails != null ?
                new ObjectParameter("dataEntryDetails", dataEntryDetails) :
                new ObjectParameter("dataEntryDetails", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertProjectDetails", dataEntryParameter, idParameter, dataEntryDetailsParameter, createdByParameter);
        }
    
        public virtual ObjectResult<string> InsertStudentDetails(string dataEntry, string id, string createdBy, string filePath, string xmlInsDate)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            var xmlInsDateParameter = xmlInsDate != null ?
                new ObjectParameter("XmlInsDate", xmlInsDate) :
                new ObjectParameter("XmlInsDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertStudentDetails", dataEntryParameter, idParameter, createdByParameter, filePathParameter, xmlInsDateParameter);
        }
    
        public virtual int InsertStudentDetails_BackUp18Feb2020(string dataEntry, string id, string createdBy, string filePath, string xmlInsDate)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            var xmlInsDateParameter = xmlInsDate != null ?
                new ObjectParameter("XmlInsDate", xmlInsDate) :
                new ObjectParameter("XmlInsDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStudentDetails_BackUp18Feb2020", dataEntryParameter, idParameter, createdByParameter, filePathParameter, xmlInsDateParameter);
        }
    
        public virtual int InsertTaskDetails(string dataEntry, string id, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTaskDetails", dataEntryParameter, idParameter, createdByParameter);
        }
    
        public virtual int InsertTestDetails(string dataEntry, string id, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTestDetails", dataEntryParameter, idParameter, createdByParameter);
        }
    
        public virtual int InsertTestkDetails(string dataEntry, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTestkDetails", dataEntryParameter, createdByParameter);
        }
    
        public virtual int InsertTestScoreDetails(string dataEntry, string id, string createdBy)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTestScoreDetails", dataEntryParameter, idParameter, createdByParameter);
        }
    
        public virtual int InsertToDoListEventDetails(string dataEntry, string usertypeId)
        {
            var dataEntryParameter = dataEntry != null ?
                new ObjectParameter("DataEntry", dataEntry) :
                new ObjectParameter("DataEntry", typeof(string));
    
            var usertypeIdParameter = usertypeId != null ?
                new ObjectParameter("UsertypeId", usertypeId) :
                new ObjectParameter("UsertypeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertToDoListEventDetails", dataEntryParameter, usertypeIdParameter);
        }
    
        public virtual ObjectResult<Logincheck_Result> Logincheck(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Logincheck_Result>("Logincheck", usernameParameter, passwordParameter);
        }
    
        public virtual int MileStoneAction(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MileStoneAction", idParameter);
        }
    
        public virtual ObjectResult<ProductDetailsInfo_Result> ProductDetailsInfo(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductDetailsInfo_Result>("ProductDetailsInfo", idParameter);
        }
    
        public virtual int Sp_InsertStatus(Nullable<int> status, string statusDetails, string fileName)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var statusDetailsParameter = statusDetails != null ?
                new ObjectParameter("StatusDetails", statusDetails) :
                new ObjectParameter("StatusDetails", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_InsertStatus", statusParameter, statusDetailsParameter, fileNameParameter);
        }
    
        public virtual ObjectResult<Sp_QuestionChecked_Result> Sp_QuestionChecked(string questionIdList)
        {
            var questionIdListParameter = questionIdList != null ?
                new ObjectParameter("QuestionIdList", questionIdList) :
                new ObjectParameter("QuestionIdList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_QuestionChecked_Result>("Sp_QuestionChecked", questionIdListParameter);
        }
    
        public virtual ObjectResult<Sp_QuestionList_Result> Sp_QuestionList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_QuestionList_Result>("Sp_QuestionList");
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_UpdateCareer(Nullable<int> careerId, string mainDescription, string subDescription, string course, string reading, string videos, string online, ObjectParameter eRROR)
        {
            var careerIdParameter = careerId.HasValue ?
                new ObjectParameter("CareerId", careerId) :
                new ObjectParameter("CareerId", typeof(int));
    
            var mainDescriptionParameter = mainDescription != null ?
                new ObjectParameter("MainDescription", mainDescription) :
                new ObjectParameter("MainDescription", typeof(string));
    
            var subDescriptionParameter = subDescription != null ?
                new ObjectParameter("SubDescription", subDescription) :
                new ObjectParameter("SubDescription", typeof(string));
    
            var courseParameter = course != null ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(string));
    
            var readingParameter = reading != null ?
                new ObjectParameter("reading", reading) :
                new ObjectParameter("reading", typeof(string));
    
            var videosParameter = videos != null ?
                new ObjectParameter("videos", videos) :
                new ObjectParameter("videos", typeof(string));
    
            var onlineParameter = online != null ?
                new ObjectParameter("online", online) :
                new ObjectParameter("online", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_UpdateCareer", careerIdParameter, mainDescriptionParameter, subDescriptionParameter, courseParameter, readingParameter, videosParameter, onlineParameter, eRROR);
        }
    
        public virtual int StudentStatusUpdate(Nullable<int> id, string status, string createdBy)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StudentStatusUpdate", idParameter, statusParameter, createdByParameter);
        }
    
        public virtual ObjectResult<sp_collegeshortlist2_Result> sp_collegeshortlist2(string councellorid)
        {
            var councelloridParameter = councellorid != null ?
                new ObjectParameter("councellorid", councellorid) :
                new ObjectParameter("councellorid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_collegeshortlist2_Result>("sp_collegeshortlist2", councelloridParameter);
        }
    
        public virtual ObjectResult<FilterDataAdmin_Result> FilterDataAdmin(string studentid, string councellorid, string collegename, string country, string city, string course, string rank, string shortlist, string applictionthrough)
        {
            var studentidParameter = studentid != null ?
                new ObjectParameter("studentid", studentid) :
                new ObjectParameter("studentid", typeof(string));
    
            var councelloridParameter = councellorid != null ?
                new ObjectParameter("councellorid", councellorid) :
                new ObjectParameter("councellorid", typeof(string));
    
            var collegenameParameter = collegename != null ?
                new ObjectParameter("collegename", collegename) :
                new ObjectParameter("collegename", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var courseParameter = course != null ?
                new ObjectParameter("course", course) :
                new ObjectParameter("course", typeof(string));
    
            var rankParameter = rank != null ?
                new ObjectParameter("rank", rank) :
                new ObjectParameter("rank", typeof(string));
    
            var shortlistParameter = shortlist != null ?
                new ObjectParameter("Shortlist", shortlist) :
                new ObjectParameter("Shortlist", typeof(string));
    
            var applictionthroughParameter = applictionthrough != null ?
                new ObjectParameter("applictionthrough", applictionthrough) :
                new ObjectParameter("applictionthrough", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FilterDataAdmin_Result>("FilterDataAdmin", studentidParameter, councelloridParameter, collegenameParameter, countryParameter, cityParameter, courseParameter, rankParameter, shortlistParameter, applictionthroughParameter);
        }
    }
}
