//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAcadenmouse
    {
        public int Id { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Class { get; set; }
        public string Year { get; set; }
        public string Board { get; set; }
        public string School { get; set; }
        public string Transcript { get; set; }
        public string OverAllGPAMark { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string Subject { get; set; }
        public string FilePath { get; set; }
        public string IsActive { get; set; }
    }
}
