//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCallNote
    {
        public int id { get; set; }
        public int STD { get; set; }
        public Nullable<System.DateTime> CallNoteDate { get; set; }
        public string Academics { get; set; }
        public string Testing { get; set; }
        public string College { get; set; }
        public string Project1 { get; set; }
        public string Project2 { get; set; }
        public string ExtraCurricular { get; set; }
        public string Misc { get; set; }
        public string Suggestedcourse { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
