//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCollegeDetailsTemp
    {
        public int Id { get; set; }
        public string CID { get; set; }
        public string EssayName { get; set; }
        public string Topic { get; set; }
        public string WordCount { get; set; }
        public string deadline { get; set; }
    }
}
