//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectMilestone
    {
        public int MId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Milestone { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Define { get; set; }
        public Nullable<bool> status { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    
        public virtual tblProject tblProject { get; set; }
    }
}
