//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentDetail
    {
        public int PID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CounsellorID { get; set; }
        public string ProductPrice { get; set; }
        public string Installment { get; set; }
        public string InstallmentNo { get; set; }
        public Nullable<System.DateTime> InstallmentDatetime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
