//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionnaireFieldLogicResult
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CareerId { get; set; }
        public string MainField { get; set; }
        public string SubField { get; set; }
        public int Critical1 { get; set; }
        public int Critical2 { get; set; }
        public int Critical3 { get; set; }
        public int HygieneFactor { get; set; }
        public int Contra1 { get; set; }
        public int Contra2 { get; set; }
        public int Result { get; set; }
    }
}
