//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionnaireSubStrength
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuestionnaireSubStrength()
        {
            this.tblQuestionnaireSubStrengthQuestions = new HashSet<tblQuestionnaireSubStrengthQuestion>();
        }
    
        public int Id { get; set; }
        public string SubStrength { get; set; }
        public string Description { get; set; }
        public Nullable<int> MainStrengthId { get; set; }
        public string IsActive { get; set; }
    
        public virtual tblQuestionnaireMainStrength tblQuestionnaireMainStrength { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuestionnaireSubStrengthQuestion> tblQuestionnaireSubStrengthQuestions { get; set; }
    }
}
