//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionnaireSubStrengthResult
    {
        public string UserName { get; set; }
        public int Artistic { get; set; }
        public int Aesthetic { get; set; }
        public int Idea_Generator { get; set; }
        public int Team_Player { get; set; }
        public int Independent { get; set; }
        public int Mentor { get; set; }
        public int Analytics { get; set; }
        public int Social_Philosophical { get; set; }
        public int Practical { get; set; }
        public decimal Average { get; set; }
    }
}
