//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionnaireFieldLogic
    {
        public int Id { get; set; }
        public string MainField { get; set; }
        public string SubField { get; set; }
        public Nullable<int> Critical1 { get; set; }
        public Nullable<int> Critical2 { get; set; }
        public Nullable<int> Critical3 { get; set; }
        public Nullable<int> HygieneFactor { get; set; }
        public Nullable<int> Contra1 { get; set; }
        public Nullable<int> Contra2 { get; set; }
        public Nullable<int> HowItWorks { get; set; }
        public string IsActive { get; set; }
    }
}
