//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public int Id { get; set; }
        public string TaskCode { get; set; }
        public string Counsellor { get; set; }
        public string Task { get; set; }
        public string Deadline { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TaskType { get; set; }
        public string EssayCount { get; set; }
        public string UniversityName { get; set; }
        public string EssayTopic { get; set; }
        public string ToStudentId { get; set; }
    }
}
